CULTURES = [
    {"name": "Việt Nam", "country": "Vietnam", "region": "Southeast Asia", "slug": "vietnam",
     "search_terms": ["vietnam", "Vietnamese"], "mb_country": "VN",
     "instruments": ["đàn tranh", "đàn bầu", "đàn nhị", "sáo", "trống"]},
    {"name": "Nhật Bản", "country": "Japan", "region": "East Asia", "slug": "japan",
     "search_terms": ["japan", "Japanese"], "mb_country": "JP",
     "instruments": ["shamisen", "koto", "shakuhachi", "taiko", "biwa"]},
    {"name": "Ấn Độ", "country": "India", "region": "South Asia", "slug": "india",
     "search_terms": ["india", "Indian"], "mb_country": "IN",
     "instruments": ["sitar", "tabla", "sarangi", "bansuri", "veena"]},
    {"name": "Indonesia", "country": "Indonesia", "region": "Southeast Asia", "slug": "indonesia",
     "search_terms": ["indonesia", "Indonesian", "Bali", "gamelan"], "mb_country": "ID",
     "instruments": ["gamelan", "angklung", "suling", "kendang", "rebab"]},
    {"name": "Brazil", "country": "Brazil", "region": "South America", "slug": "brazil",
     "search_terms": ["brazil", "Brazilian", "samba", "capoeira"], "mb_country": "BR",
     "instruments": ["berimbau", "pandeiro", "cavaquinho", "agogô", "reco-reco"]},
    {"name": "Nigeria", "country": "Nigeria", "region": "West Africa", "slug": "nigeria",
     "search_terms": ["nigeria", "Nigerian", "Yoruba", "Hausa"], "mb_country": "NG",
     "instruments": ["talking drum", "shekere", "udu", "kalimba", "gangan"]},
    {"name": "Maroc", "country": "Morocco", "region": "North Africa", "slug": "morocco",
     "search_terms": ["morocco", "Moroccan", "Maghreb"], "mb_country": "MA",
     "instruments": ["oud", "guembri", "qraqeb", "ney", "tar"]},
    {"name": "Thổ Nhĩ Kỳ", "country": "Turkey", "region": "Middle East", "slug": "turkey",
     "search_terms": ["turkish", "Anatolia", "Turk"], "mb_country": "TR",
     "instruments": ["ney", "saz", "kemençe", "darbuka", "kanun"]},
    {"name": "Hy Lạp", "country": "Greece", "region": "Europe", "slug": "greece",
     "search_terms": ["greece", "Greek", "Hellenic"], "mb_country": "GR",
     "instruments": ["bouzouki", "lyra", "baglama", "daouli", "zournas"]},
    {"name": "Ireland", "country": "Ireland", "region": "Europe", "slug": "ireland",
     "search_terms": ["ireland", "Irish", "Celtic"], "mb_country": "IE",
     "instruments": ["fiddle", "uilleann pipes", "bodhrán", "tin whistle", "harp"]},
    {"name": "Mali", "country": "Mali", "region": "West Africa", "slug": "mali",
     "search_terms": ["mali", "Malian", "Mande", "Bambara"], "mb_country": "ML",
     "instruments": ["kora", "balafon", "ngoni", "djembe", "cora"]},
    {"name": "Cuba", "country": "Cuba", "region": "Caribbean", "slug": "cuba",
     "search_terms": ["cuba", "Cuban", "Afro-Cuban"], "mb_country": "CU",
     "instruments": ["claves", "maracas", "bongo", "tres", "güiro"]},
    {"name": "México", "country": "Mexico", "region": "North America", "slug": "mexico",
     "search_terms": ["mexico", "Mexican", "Maya", "Aztec"], "mb_country": "MX",
     "instruments": ["marimba", "guitarrón", "vihuela", "huéhuetl", "jarana"]},
    {"name": "Hàn Quốc", "country": "South Korea", "region": "East Asia", "slug": "korea",
     "search_terms": ["korea", "Korean"], "mb_country": "KR",
     "instruments": ["gayageum", "janggu", "piri", "taepyeongso", "geomungo"]},
    {"name": "Thái Lan", "country": "Thailand", "region": "Southeast Asia", "slug": "thailand",
     "search_terms": ["thailand", "Thai"], "mb_country": "TH",
     "instruments": ["ranat", "khong wong", "khèn", "saw duang", "chakhe"]},
    {"name": "Iran", "country": "Iran", "region": "Middle East", "slug": "iran",
     "search_terms": ["iran", "Persian"], "mb_country": "IR",
     "instruments": ["setar", "santur", "kamancheh", "daf", "tonbak"]},
    {"name": "Jamaica", "country": "Jamaica", "region": "Caribbean", "slug": "jamaica",
     "search_terms": ["jamaica", "Jamaican", "reggae"], "mb_country": "JM",
     "instruments": ["steel drum", "reggae guitar", "bass", "drum kit"]},
    {"name": "Ai Cập", "country": "Egypt", "region": "North Africa", "slug": "egypt",
     "search_terms": ["egypt", "Egyptian"], "mb_country": "EG",
     "instruments": ["oud", "qanun", "nay", "riq", "darbuka"]},
    {"name": "Scotland", "country": "Scotland", "region": "Europe", "slug": "scotland",
     "search_terms": ["scotland", "Scottish", "Highland"], "mb_country": "GB",
     "instruments": ["bagpipes", "fiddle", "accordion", "clarsach", "bodhrán"]},
    {"name": "Mông Cổ", "country": "Mongolia", "region": "Central Asia", "slug": "mongolia",
     "search_terms": ["mongolia", "Mongolian"], "mb_country": "MN",
     "instruments": ["morin khuur", "yochin", "limbe", "igil", "khöömei"]},
]
